/*********************************************************************************
 _____ ____  _____ 
|  _  |    \|   __|
|     |  |  |   __|
|__|__|____/|__|   
ARMA Mission Development Framework
ADF version: 2.06 / JUN 2018

Script: Respawn init 
Author: Whiztler
Script version: 3.0

File: ADF_onPlayerKilled.sqf
**********************************************************************************
DO NOT edit this file. To set-up and configure your mission, edit the files in
the  '\mission\'  folder.
*********************************************************************************/

if (ADF_debug || time < 180) then {diag_log "ADF RPT: Init - executing: ADF_onPlayerKilled.sqf"}

// Init
params ["_o","_k","_r","_t"];
private _u 	= player;

// No respawn (0) or Bird respawn (1) > 140B05
if ((getNumber (missionConfigFile >> "respawn")) < 2) exitWith {
	if (ADF_mod_TFAR) then {[player, true] call TFAR_fnc_forceSpectator};
	if (ADF_mod_ACRE) then {[true] call acre_api_fnc_setSpectator};
}; 

// Check if respawn-tickets are enabled and check if there are no more tickets left. If true evoke spectator.
if (	ADF_Tickets && (((side _u == west) && (([west] call BIS_fnc_respawnTickets) < 1)) || ((side _u == east) && (([east] call BIS_fnc_respawnTickets) < 1)))) exitWith {
	if (ADF_mod_ACE3) then {
		_u setVariable ["ACE_Medical_hasPain", false];
		_u setVariable ["ACE_Medical_isBleeding", false];
		_u setVariable ["ACE_isUnconscious", false];
		[false] call ACE_Common_fnc_disableUserInput;
		ace_hearing_disableVolumeUpdate = true;
	};
	"chromAberration" ppEffectEnable false;	
	[_u, _o, true] call f_fnc_CamInit; // force into F3 Spectator > 140B05
};

// Save the player loadout when ACE3 SameGearRespawn is NOT enabled
if (ADF_sameGearRespawn && !ADF_mod_ACE3) then {[_u, "SAVE"] call ADF_fnc_storeLoadout};

// Wait till the player respawns
waitUntil {alive _u};

// Disable 3rd person view?
if (ADF_disable3PC || ADF_disable3PV) then {player spawn ADF_fnc_disable3P};

//  Respawn params/vars - announce (hint) number of remaining respawn tickets per side
if (ADF_Tickets) then {
	if (side player == west) then {
		private _m = parseText format ["<t color='#6C7169' size='1.5'>%1 Logistics</t><br/><br/><t color='#A1A4AD' align='left'>Reinforcement slot:</t><t color='#FFFFFF' align='right'>%2</t><br/><t color='#1262c4' align='left'>BLUEFOR</t><t color='#A1A4AD' align='left'> slots remaining: </t><t color='#FFFFFF' align='right'>%3</t><br/>",ADF_clanName, name player, [west] call BIS_fnc_respawnTickets];
		_m remoteExec ["hintSilent", west, false];		
		sleep 8;
		hintSilent "";
	};

	if (side player == east) then {
		private _m = parseText format ["<t color='#6C7169' size='1.5'>%1 Logistics</t><br/><br/><t color='#A1A4AD' align='left'>Reinforcement slot:</t><t color='#FFFFFF' align='right'>%2</t><br/><t color='#d45454' align='left'>OPFOR</t><t color='#A1A4AD' align='left'> slots remaining: </t><t color='#FFFFFF' align='right'>%3</t><br/>",ADF_clanName, name player, [east] call BIS_fnc_respawnTickets];
		_m remoteExec ["hintSilent",east, false];	
		sleep 8;
		hintSilent "";
	};
};

// Use the ACE3 function rather than the ADF function
if (ADF_mod_ACE3 && ADF_sameGearRespawn) exitWith {if (ADF_Clan_uniformInsignia) then {[_u,"CLANPATCH"] call BIS_fnc_setUnitInsignia};}; 

///// Apply stored Loadout
[_u, "LOAD"] call ADF_fnc_storeLoadout;
if (ADF_Clan_uniformInsignia) then {[_u,"CLANPATCH"] call BIS_fnc_setUnitInsignia};

// Altitude Based Fatigue
if (ADF_ABF) then {execVM "ADF\ADF_init_abf.sqf"};