/*********************************************************************************
 _____ ____  _____ 
|  _  |    \|   __|
|     |  |  |   __|
|__|__|____/|__|   
ARMA Mission Development Framework
ADF version: 2.06 / JUN 2018

Script: Mission init / Init reporting
Author: Whiztler
Script version: 1.20

File: ADF_init_rpt.sqf
**********************************************************************************
DO NOT edit this file. To set-up and configure your mission, edit the files in
the  '\mission\'  folder.
*********************************************************************************/

// Reporting
if (ADF_debug || ADF_extRpt || time < 180) then {diag_log "ADF RPT: Init - executing: ADF_init_rpt.sqf"};

// Init
private _m	= "";
private _msg	= "";
private _hc	= count (entities "HeadlessClient_F");
private _ai	= (count (allUnits - allPlayers)) - _hc;
if (_ai < 0) then {_ai = 0};

// Report included mods supported by ADF
if (ADF_mod_CBA) then {_m = _m + "CBA A3"};
if (ADF_mod_ACRE) then {_m = _m + ", ACRE2"};
if (ADF_mod_TFAR) then {_m = _m + ", TFAR"};
if (ADF_mod_CTAB) then {_m = _m + ", cTab"};
if (ADF_mod_ACE3) then {_m = _m + ", ACE3"};
if (ADF_mod_Ares) then {_m = _m + ", Ares"};
if (ADF_mod_CSAT) then {_m = _m + ", TEC CSAT"};
if (ADF_mod_RHS) then {_m = _m + ", RHS"};
if (ADF_mod_JR) then {_m = _m + ", ASDG JR"};
if (ADF_mod_NIARMS) then {_m = _m + ", NIarms"};
if (ADF_mod_CUP_T || ADF_mod_AIA) then {_m = _m + ", CUP Terrains"};
if (ADF_mod_CUP_W) then {_m = _m + ", CUP Weapons"};
if (ADF_mod_CUP_U) then {_m = _m + ", CUP Units"};
if (ADF_mod_CUP_V) then {_m = _m + ", CUP Vehicles"};
if (ADF_mod_ASRAI) then {_m = _m + ", ASR AI"};
if (ADF_mod_VCOMAI) then {_m = _m + ", vCom AI"};
if (ADF_mod_BCOMBAT) then {_m = _m + ", bCombat"};

// Init reporting
if (ADF_debug) then {
	diag_log "--------------------------------------------------------------------------------------";
	_msg = format ["Init - ADF version: %1",ADF_tpl_version];
	[_msg, false] call ADF_fnc_log;
	_msg = format ["Init - Mission version: %1",ADF_mission_version];
	[_msg, false] call ADF_fnc_log;
	_msg = format ["Init - Number of players connected: %1", count allPlayers];
	[_msg, false] call ADF_fnc_log;
	_msg = format ["Init - Number of HC's connected: %1", _hc];
	[_msg, false] call ADF_fnc_log;	
	_msg = format ["Init - Number of AI's active: %1", _ai];
	[_msg, false] call ADF_fnc_log;
	diag_log "--------------------------------------------------------------------------------------";
} else { // Live mission logging
	diag_log ""; diag_log "";
	diag_log "--------------------------------------------------------------------------------------";
	diag_log format ["ADF RPT: Init - ADF version: %1", ADF_tpl_version];
	diag_log "--------------------------------------------------------------------------------------";
	diag_log format ["ADF RPT: Init - Mission version: %1", ADF_mission_version];
	diag_log format ["ADF RPT: Init - Mission name: %1", (getText (missionConfigFile >> "overviewText"))];
	diag_log format ["ADF RPT: Init - Mission developer: %1", (getText (missionConfigFile >> "author"))];
	diag_log "--------------------------------------------------------------------------------------";
	diag_log format ["ADF RPT: Init - Number of players connected: %1", (count allPlayers) - _hc];
	diag_log format ["ADF RPT: Init - Number of HC's connected: %1", _hc];
	diag_log "--------------------------------------------------------------------------------------";
	diag_log format ["ADF RPT: Init - Number of AI's active: %1", _ai];
	diag_log "--------------------------------------------------------------------------------------";
	diag_log format ["ADF RPT: Init - ADF autodetect addons loaded: %1", _m];
	diag_log "--------------------------------------------------------------------------------------";
	diag_log "ADF_debug mode is disabled (set to 'disable') in the mission params. To debug missions";
	diag_log "enable 'Mission Debug' in the in mission parameters during slotting in.";
	diag_log "--------------------------------------------------------------------------------------";
	diag_log ""; diag_log "";
};

// Server FPS reporting in RPT. The frequency of the reporting is based on server performance.
if (ADF_extRpt) then {[60, "Server", "Server"] spawn ADF_fnc_statsReporting};