/*********************************************************************************
 _____ ____  _____ 
|  _  |    \|   __|
|     |  |  |   __|
|__|__|____/|__|   
ARMA Mission Development Framework
ADF version: 2.06 / JUN 2018

Script: Mission pre-init
Author: Whiztler
Script version: 1.31

File: ADF_init_pre.sqf
**********************************************************************************
DO NOT edit this file. To set-up and configure your mission, edit the files in
the  '\mission\'  folder.
*********************************************************************************/

// Reporting
if (ADF_debug || ADF_extRpt || time < 180) then {diag_log "ADF RPT: Init - executing: ADF_init_pre.sqf"};

// Determine the client and stamp the RPT with the client that is executing this script.
private _e = "PLAYER CLIENT";
private _n = "";
if (!hasInterface && !isDedicated) then {_e = "HEADLESS CLIENT"; _n = format ["(%1)", name player]};
if (isServer) then {_e = "SERVER"};
if (isDedicated) then {_e = "DEDICATED SERVER"};

diag_log ""; diag_log "";
diag_log "--------------------------------------------------------------------------------------";
diag_log "ARMA Development Framework (ADF)";
diag_log format ["Reporting entity: %1 %2", _e, _n];
diag_log "--------------------------------------------------------------------------------------";
diag_log ""; diag_log "";

// Get addon/mod/dlc availability from the A3 config file and store them in easy to use variables
ADF_dlc_MarksMan 	= isClass (configFile >> "CfgMods" >> "Mark"); // Marksman DLC
ADF_dlc_Bundle 	= isClass (configFile >> "CfgMods" >> "DLCBundle"); // DLC Bundle
ADF_dlc_Bundle2 	= isClass (configFile >> "CfgMods" >> "DLCBundle"); // DLC Bundle 2
ADF_dlc_Heli 		= isClass (configFile >> "CfgMods" >> "Heli"); // Helicopters DLC
ADF_dlc_Apex 		= isClass (configFile >> "CfgMods" >> "Expansion"); // Apex/Tanoa
ADF_dlc_LawsofWar	= isClass (configFile >> "CfgMods" >> "Orange"); // Laws of War
ADF_dlc_TacOps	= isClass (configFile >> "CfgMods" >> "Tacops"); // Tac-Ops

ADF_mod_CBA 		= isClass (configFile >> "CfgPatches" >> "cba_main"); // CBA_A3
ADF_mod_ACRE 		= isClass (configFile >> "CfgPatches" >> "acre_main"); // ACRE2
ADF_mod_TFAR 		= isClass (configFile >> "CfgPatches" >> "task_force_radio"); // TFAR
ADF_mod_CTAB 		= isClass (configFile >> "CfgPatches" >> "cTab"); // cTAB
ADF_mod_ACE3 		= isClass (configFile >> "CfgPatches" >> "ace_common"); // ACE3 
ADF_mod_ASRAI		= isClass (configFile >> "CfgPatches" >> "asr_ai3_main"); // ASR AI
ADF_mod_VCOMAI	= isClass (configFile >> "CfgPatches" >> "vcomai"); // vCom AI
ADF_mod_BCOMBAT	= isClass (configFile >> "CfgPatches" >> "bcombat"); // bCombat
ADF_mod_AIA	 	= isClass (configFile >> "CfgPatches" >> "AiA_Core"); // All in Arma (Terrain Pack)
ADF_mod_Ares 		= isClass (configFile >> "CfgPatches" >> "Ares"); // Ares Zeus
ADF_mod_CSAT 		= isClass (configFile >> "CfgPatches" >> "TEC_CSAT"); // TEC CSAT
ADF_mod_RHS	 	= isClass (configFile >> "CfgPatches" >> "rhs_main"); // Red Hammer Studios USAF & AFRF
ADF_mod_CUP_T 	= isClass (configFile >> "CfgPatches" >> "CUP_Terrains_Core"); // CUP Terrains Maps
ADF_mod_CUP_W 	= isClass (configFile >> "CfgPatches" >> "CUP_Weapons_WeaponsCore"); // CUP Weapons
ADF_mod_CUP_U 	= isClass (configFile >> "CfgPatches" >> "CUP_Creatures_People_Core"); // CUP Units
ADF_mod_CUP_V 	= isClass (configFile >> "CfgPatches" >> "CUP_WheeledVehicles_Core"); // CUP Vehicles
ADF_mod_JR	 	= isClass (configFile >> "CfgPatches" >> "asdg_jointrails"); // ASDG Joint Rails
ADF_mod_NIARMS	= isClass (configFile >> "CfgPatches" >> "hlc_core"); // HLC / NIArms

// Init global mission vars
ADF_missionInit 		= false;
ADF_HC_execute		= false;
MotsActive			= false;
ADF_init_AO			= false;
ADF_debug_IED			= false;
ADF_debug_bPos		= false;
ADF_vStrip			= true;
ADF_microDAGR_all 	= 0; 
ADF_TFAR_LR_freq 		= 0;
ADF_TFAR_SW_freq 		= 0;
ADF_set_callSigns 	= false;
ADF_set_radios 		= false;
ADF_isHC 			= false;
ADF_GM_init			= false;
ADF_ABF 				= false;
ADF_microDAGR 		= "";
ADF_gearLoaded		= false;
ADF_cntHC 			= 0;
ADF_log_rptMods 		= "";
ADF_isHC1			= false;
ADF_isHC2			= false;
ADF_isHC3			= false;
ADF_debug_bPos		= false;
ADF_mapLoaded			= "Altis";
if (isNil "ADF_HC_connected") then {ADF_HC_connected = false;}; // HC init

// Disable AI chatter. In multiplayer for players only
If (hasInterface) then {player setVariable ["BIS_noCoreConversations", true]};
if (isMultiplayer) then {{[[_x, "NoVoice"]] remoteExec ["setSpeaker", -2, true]} forEach allPlayers;} else {enableSentences false};