/*********************************************************************************
 _____ ____  _____ 
|  _  |    \|   __|
|     |  |  |   __|
|__|__|____/|__|   
ARMA Mission Development Framework
ADF version: 2.06 / JUN 2018

Script: Mission initialization countdown timer
Author: Whiztler
Script version: 1.51

File: ADF_init_post.sqf
**********************************************************************************
DO NOT edit this file. To set-up and configure your mission, edit the files in
the  '\mission\'  folder.
*********************************************************************************/

// Reporting
if (ADF_debug || ADF_extRpt || time < 180) then {diag_log "ADF RPT: Init - executing: ADF_init_post.sqf"};

if (ADF_debug) then {
	{
		private _m = "DIAG - Script executed: " + str _x;
		[_m, false] call ADF_fnc_log;
	} forEach diag_activeSQFScripts;
};

// Init
params ["_t","_vt","_vm","_db","_dn"];
private _u 	= player;
private _c	= 0;
_t 	= _t / 100;

// Check debug, locality, etc
if (time > 300) exitWith {ADF_missionInit = true;};
if (ADF_debug) exitWith {ADF_missionInit = true; publicVariable "ADF_missionInit"; diag_log "ADF RPT: INIT - debug mode detected, skipping mission init timer"};
if (isMultiplayer) then {_u enableSimulation false; showMap false;};

// check ADF build
If ((_db == "Alpha") || (_db == "Beta")) then {
	private _m = format ["This is a development build of ADF (%1 - %2 %3). Do not use for live missions!", _vt, _db, _dn];
	_m remoteExec ["systemChat", -2, false];
};

// Init client display		
while {(_c != 100)} do {
	_c = _c + 1;	
	private _m = format ["<br/><t align='left' size='1.1' color='#A1A4AD'>Mission Initializing: </t><t size='1.1' align='left' color='#F7D358' font='PuristaBold'>%1&#0037;</t><t size='1.1' align='left' color='#A1A4AD'> done</t><br/><br/><t align='left' color='#A1A4AD'>- Refrain from moving!</t><br/><t align='left' color='#A1A4AD'>- Do not use your radio!</t><br/><t align='left' color='#A1A4AD'>- Follow TL orders</t><br/><t align='left' color='#A1A4AD'>- Init takes approx %2 secs</t><br/><br/><t align='left' color='#A1A4AD'>Tpl: <t color='#FFFFFF' align='left'>%3</t>  |  Mission: </t><t color='#FFFFFF' align='left'>%4</t><br/><br/>", _c, _t * 100, _vt, _vm];

	If ((_db == "Alpha") || (_db == "Beta")) then {
		_m = _m + format ["
			<t align='left' color='#A1A4AD'>Build: <t color='#FFFFFF' align='left'>%1</t>  |  Build version: </t><t color='#FFFFFF' align='left'>%2</t><br/>
		", _db, _dn];
	};
	
	sleep _t;
	hintSilent parseText _m; 
};

if (isMultiplayer) then {_u enableSimulation true; showMap true;};

private _m = format ["<br/><t size='1.1' color='#FFFFFF' align='left'>Mission initializing complete</t><t size='1' align='left' color='#A1A4AD'><br/><br/>- Refrain from moving!<br/>- Do not use your radio!<br/>- Follow TL orders<br/>- Init takes approx %1 secs<br/><br/>Tpl: %2  |  Mission: %3</t><br/><br/>", _t * 100, _vt, _vm];

If ((_db == "Alpha") || (_db == "Beta")) then {
	_m = _m + format ["
		<t align='left' color='#A1A4AD'>Build: %1 | Build version: %2</t><br/>
	", _db, _dn];
};

hintSilent parseText _m;
finishMissionInit;
sleep 3;
hintSilent "";
ADF_missionInit = true; 

// Debug reporting
if (ADF_debug) then {diag_log "ADF Debug: INIT - ADF_missionInit = true"};
