/*********************************************************************************
 _____ ____  _____ 
|  _  |    \|   __|
|     |  |  |   __|
|__|__|____/|__|   
ARMA Mission Development Framework
ADF version: 2.06 / JUN 2018

Script: Group Init / Call Signs . Radio Init/Config
Author: Whiztler
Script version: 2.66

File: ADF_init_comm.sqf
**********************************************************************************
DO NOT edit this file. To set-up and configure your mission, edit the files in
the  '\mission\'  folder.
*********************************************************************************/

// Reporting
if (time < 180) then {diag_log "ADF RPT: Init - executing: ADF_init_comm.sqf"};

// HC exits script
if (ADF_isHC) exitWith {};

////  Init

params [
	["_preset", "WOLFPACK", [""]],
	["_ADF_ACRE_fullDuplex", true, [false]],
	["_ADF_ACRE_interference", true, [false]],
	["_ADF_ACRE_AIcanHear", true, [false]],
	["_ADF_TFAR_microDAGR", false, [true]]
];

ADF_roster_uArray = if (isMultiplayer) then {playableUnits} else {switchableUnits};
ADF_roster_uName 	= "";
ADF_roster_Intro	= "";
ADF_roster_line 	= "";

waitUntil {ADF_gearLoaded}; 
if !(isNil "GM_1") then {if (player == GM_1) then {waitUntil {ADF_GM_init}}};  
if !(isNil "GM_2") then {if (player == GM_2) then {waitUntil {ADF_GM_init}}};  

//// Load and apply preset

if (ADF_debug) then {diag_log format ["ADF Debug: ADF_init_comm - %1 preset Settings for %2 - Group: %3 - Callsign: %4", _preset, name player, group player, groupID (group player)]};
private _s = {
	if (ADF_debug) then {diag_log format ["ADF Debug: ADF_init_comm - Preset done for %1 (%2), Group: %3, Callsign: %4, SW: %5 - LR: %6",name player, player, group player, groupID (group player), ADF_TFAR_SW_freq, ADF_TFAR_LR_freq]};
	ADF_set_callSigns = true;	
};

switch (_preset) do {
    case "WOLFPACK":	{
		
		switch (groupID (group player)) do {
			case "gCO_41M"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["WOLF-1"]}; ADF_TFAR_LR_freq = 50; ADF_TFAR_SW_freq = 100};
			case "gCO_41R"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["WOLF-2"]}; ADF_TFAR_LR_freq = 50; ADF_TFAR_SW_freq = 200};
			case "gCO_41Y"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["WOLF-3"]}; ADF_TFAR_LR_freq = 50; ADF_TFAR_SW_freq = 300};
			case "gGM"		: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["INSTRUCTOR"]}; ADF_TFAR_LR_freq = 35; ADF_TFAR_SW_freq = 350};
		};
		player call _s;		
	};
    
	case "2SIERRA":	{
		
		switch (groupID (group player)) do {
			case "2 PLATOON"	;
			case "gCO_1": {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2 PLT"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 100};
			case "2-1 SQUAD"	;
			case "gCO_11": {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2-1 SQUAD"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 110};
			case "2-2 SQUAD"	;
			case "gCO_12": {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2-2 SQUAD"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 120};
			case "2-3 SQUAD";
			case "gCO_13": {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2-3 SQUAD"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 130};
			case "SUPPORT";
			case "gCO_2": {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2-4 SUPPORT"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 140};		
		};
		player call _s;
		
	};
	
	case "1STRECON":	{
		
		switch (groupID (group player)) do {
			case "gCO_CMD"		: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["CO CMD"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 100};
			case "gCO_A_SQD"		: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["ALPHA SQ"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 110};
			case "gCO_B_SQD"		: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["BRAVO SQ"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 111};
			case "gCO_C_SQD"		: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["CHARLIE SQ"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 112};
			case "gCO_COWBOY"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["COWBOY"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 120};
			case "gCO_HAWK"		: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["HAWK"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 130};
		};
		player call _s;
		
	};	
    
	case "DEFAULT";	
    default 			{
		
		switch (groupID (group player)) do {
			case "gCC"		: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["CO CMD"]}; ADF_TFAR_LR_freq = 30; ADF_TFAR_SW_freq = 55;};
			
			case "gCO_1"		: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["1 PLT"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 100;};
			case "gCO_11"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["1-1 SQUAD"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 110;};
			case "gCO_11A"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["1-1 ALPHA"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 111;};
			case "gCO_11B"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["1-1 BRAVO"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 112;};
			case "gCO_12"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["1-2 SQUAD"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 120;};
			case "gCO_12A"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["1-2 ALPHA"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 121;};
			case "gCO_12B"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["1-2 BRAVO"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 122;};
			case "gCO_13"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["1-3 SQUAD"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 130;};
			case "gCO_13A"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["1-3 ALPHA"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 131;};
			case "gCO_13B"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["1-3 BRAVO"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 132;};
			case "gCO_13C"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["1-3 CHARLIE"]}; ADF_TFAR_LR_freq = 40; ADF_TFAR_SW_freq = 133;};
			
			case "gCO_2"		: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2 BAT"]}; ADF_TFAR_LR_freq = 50; ADF_TFAR_SW_freq = 200;};
			case "gCO_21A"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2-1 ALPHA"]}; ADF_TFAR_LR_freq = 50; ADF_TFAR_SW_freq = 210;};
			case "gCO_21B"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2-1 BRAVO"]}; ADF_TFAR_LR_freq = 50; ADF_TFAR_SW_freq = 211;};
			case "gCO_21C"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2-1 CHARLIE"]}; ADF_TFAR_LR_freq = 50; ADF_TFAR_SW_freq = 212;};
			case "gCO_22A"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2-2 ALPHA"]}; ADF_TFAR_LR_freq = 50; ADF_TFAR_SW_freq = 220;};
			case "gCO_22b"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2-2 BRAVO"]}; ADF_TFAR_LR_freq = 50; ADF_TFAR_SW_freq = 221;};
			case "gCO_23A"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2-3 ALPHA"]}; ADF_TFAR_LR_freq = 50; ADF_TFAR_SW_freq = 230;};
			case "gCO_23b"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["2-3 BRAVO"]}; ADF_TFAR_LR_freq = 50; ADF_TFAR_SW_freq = 231;};
			
			case "gCO_3"		: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["3 WING"]}; ADF_TFAR_LR_freq = 60; ADF_TFAR_SW_freq = 300;};
			case "gCO_31A"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["3-1 ALPHA"]}; ADF_TFAR_LR_freq = 60; ADF_TFAR_SW_freq = 310;};
			case "gCO_31B"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["3-1 BRAVO"]}; ADF_TFAR_LR_freq = 60; ADF_TFAR_SW_freq = 311;};
			case "gCO_32A"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["3-2 ALPHA"]}; ADF_TFAR_LR_freq = 60; ADF_TFAR_SW_freq = 320;};
			case "gCO_32B"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["3-2 BRAVO"]}; ADF_TFAR_LR_freq = 60; ADF_TFAR_SW_freq = 321;};
			case "gCO_32C"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["3-2 CHARLIE"]}; ADF_TFAR_LR_freq = 60; ADF_TFAR_SW_freq = 322;};
			case "gCO_33A"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["3-3 ALPHA"]}; ADF_TFAR_LR_freq = 60; ADF_TFAR_SW_freq = 330;};
			case "gCO_33A"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["3-3 BRAVO"]}; ADF_TFAR_LR_freq = 60; ADF_TFAR_SW_freq = 331;};
			
			case "gCO_4"		: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["4 SQDR"]}; ADF_TFAR_LR_freq = 70; ADF_TFAR_SW_freq = 400;};
			case "gCO_41M"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["4-1 MIKE"]}; ADF_TFAR_LR_freq = 70; ADF_TFAR_SW_freq = 410;};
			case "gCO_41R"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["4-1 ROMEO"]}; ADF_TFAR_LR_freq = 70; ADF_TFAR_SW_freq = 411;};
			case "gCO_41Y"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["4-1 YANKEE"]}; ADF_TFAR_LR_freq = 70; ADF_TFAR_SW_freq = 412;};
			case "gCO_41Z"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["4-1 ZULU"]}; ADF_TFAR_LR_freq = 70; ADF_TFAR_SW_freq = 413;};
			case "gCO_42A"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["4-2 TANGO"]}; ADF_TFAR_LR_freq = 70; ADF_TFAR_SW_freq = 420;};
			case "gCO_42B"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["4-2 VICTOR"]}; ADF_TFAR_LR_freq = 70; ADF_TFAR_SW_freq = 421;};
			case "gCO_43F"	: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["4-3 FOXTROT"]}; ADF_TFAR_LR_freq = 80; ADF_TFAR_SW_freq = 430;};
			
			case "gGM"		: {if (player == leader (group player)) then {(group player) setGroupIdGlobal ["HADES"]}; ADF_TFAR_LR_freq = 35; ADF_TFAR_SW_freq = 350;};
		};
		player call _s;		
	};
};

// Vars
private _ur 		= "";
private _g_old 	= grpNull;
private _g_new	= grpNull;

///// TFAR pre-init

if (ADF_mod_TFAR) then {
	waitUntil {time > 5};
	TF_give_microdagr_to_soldier = _ADF_TFAR_microDAGR;
	tf_give_personal_radio_to_regular_soldier = false; // Commander radio for all players
	tf_no_auto_long_range_radio = true; // LR radio for leaders
	TF_speakerDistance = 20; // The propagation distance of sound from radio speakers.
	
	 // 0 - 1 The volume (gain level) of direct speech — does not affect the propagation distance.
	player setVariable ["tf_voiceVolume", 1.0, true];
	 // 0 -1 Global volume for radio and speech.
	player setVariable ["tf_globalVolume", 1.0];
	 // 1-2 A multiplier for increasing, or lowering the distance from transmitter to receiver
	player setVariable ["tf_receivingDistanceMultiplicator", 1];
	// 0-1 A multiplier for increasing or lowering the range of transmission.
	player setVariable ["tf_sendingDistanceMultiplicator", 1.0]; 	
	
	// Sets the maximum range (meters) of transmission for a vehicle-mounted radio.
	{ 
		if ((side _x == ADF_playerSide) && ((_x isKindOf "Tank") || (_x isKindOf "car"))) then {
		_x setVariable ["tf_range", 30000, true] 
		};
	} forEach vehicles;
	
	if (side player != ADF_playerSide) exitWith {};
	
	// Check preset preferences
	if (ADF_TFAR_preset) then {
		tf_same_sw_frequencies_for_side = false;
	} else {
		ADF_TFAR_SW_freq_west = [
			"55",
			"100","110","111","112","120","121","122","130","131","132","133",
			"200","210","211","212","220","221","230","231",
			"300","310","311","320","321","322","330","331",
			"350",
			"400","410","411","412","413","420","421","430"
		];
		ADF_TFAR_LR_freq_west = ["30","40","50","60","70","80","35"];
		tf_freq_west = [0 ,7, ADF_TFAR_SW_freq_west, 0, tf_west_radio_code, -1, 0, getPlayerUID player, false];
		tf_freq_west_lr = [0 ,7, ADF_TFAR_SW_freq_west, 0, tf_west_radio_code, -1, 0, false];
	};
};


///// ACRE2 pre-init

if (ADF_mod_ACRE) then { 
	private _ADF_ACRE_init = [] call acre_api_fnc_isInitialized;
	waitUntil {_ADF_ACRE_init};
	[_ADF_ACRE_fullDuplex] call acre_api_fnc_setFullDuplex;
	[_ADF_ACRE_interference] call acre_api_fnc_setInterference;
	[_ADF_ACRE_AIcanHear] call acre_api_fnc_setRevealToAI;
	
	if hasInterface then {
		{_x call acre_api_fnc_babelAddLanguageType} forEach f_radios_settings_acre2_languages;
		if (!alive player) exitWith {[true] call acre_api_fnc_setSpectator;};
	};	
	
	if (ADF_debug) then {["ADF_init_comm - ACRE settings initialized", false] call ADF_fnc_log};
};

// Initialize ACE3 BluForce Tracking (if activated)
if (ADF_mod_ACE3 && (ADF_microDAGR == "ACE_microDAGR")) then { //  140B06
	// insert Blueforce tracking init
	ace_map_BFT_Enabled = true;
	ace_map_BFT_markers = [];
	[ace_map_fnc_blueForceTrackingUpdate, 1, []] call CBA_fnc_addPerFrameHandler;	
	if (ADF_debug) then {["ADF_init_comm - ACE3 BluForce Tracking initialized", false] call ADF_fnc_log};
};

///// Apply the Radio Frequencies

if (hasInterface) then {waitUntil {ADF_set_callSigns}};

// Set the frequencies for TFAR
if (ADF_mod_TFAR && ADF_TFAR_preset && hasInterface) then {
	// finish init, 15 secs in case of debug
	waitUntil {time > 15 && ADF_missionInit}; 
	
	_ADF_TFAR_SW_radio = call TFAR_fnc_haveSWRadio;
	_ADF_TFAR_LR_radio = call TFAR_fnc_haveLRRadio;
	
	// Apply SW & LR frequencies
	if (_ADF_TFAR_SW_radio) then {[(call TFAR_fnc_activeSwRadio), 1, str ADF_TFAR_SW_freq] call TFAR_fnc_SetChannelFrequency};
	if (_ADF_TFAR_LR_radio) then {[(call TFAR_fnc_activeLrRadio), 1, str ADF_TFAR_LR_freq] call TFAR_fnc_SetChannelFrequency};
	if (ADF_debug) then {["ADF_init_comm - TFAR radios configured", false] call ADF_fnc_log};
	
	// Announce to player
	if (!_ADF_TFAR_LR_radio && _ADF_TFAR_SW_radio) then {systemChat format ["%1: %2, TFAR radio tuned in. SW: %3", ADF_clanTAG, name vehicle player, ADF_TFAR_SW_freq]};
	if (_ADF_TFAR_LR_radio && !_ADF_TFAR_SW_radio) then {systemChat format ["%1: %2,  TFAR radio tuned in. LR: %3", ADF_clanTAG, name vehicle player, ADF_TFAR_LR_freq]};
	if (_ADF_TFAR_LR_radio && _ADF_TFAR_LR_radio) then {systemChat format ["%1: %2,  TFAR radio's tuned in. SW: %3 | LR: %4", ADF_clanTAG, profileName, ADF_TFAR_SW_freq, ADF_TFAR_LR_freq]};
	if (!_ADF_TFAR_LR_radio && !_ADF_TFAR_SW_radio) then {systemChat format ["%1: %2,  You do not carry a TFAR radio. No frequencies configured.", ADF_clanTAG, name vehicle player, ADF_TFAR_LR_freq]};
	ADF_set_radios = true;
	
	// Apply the commDetetct event handler
	["commDetect", "OnSpeak", {[_this select 0] call ADF_fnc_commDetect}, player] call TFAR_fnc_addEventHandler;
};

// Set the frequencies for ACRE2
if (ADF_mod_ACRE && ADF_ACRE_preset) then {
	// Apply ACRE channels WIP
	ADF_set_radios = true;
	if (ADF_debug) then {["ADF_init_comm - ACRE2 radios configured", false] call ADF_fnc_log};
};

// Set radios to true in case TFAR and ACRE are not active
if !(ADF_mod_ACRE && ADF_mod_TFAR) then {ADF_set_radios = true;};

///// Create the roster
if (isDedicated) exitWith {};

// Create the Roster Subject
player createDiarySubject ["Deployment Roster",ADF_clanName + " Roster"];

// Roster create loop
{
	if (side _x == side player) then {
		_g_new = group _x;
		_ADF_roster_uGroup = _g_new;
		_ADF_roster_uGroupName = groupID (_g_new);
		ADF_roster_userGroup = "";
		_ur = " (" + getText(configFile >> "CfgVehicles" >> typeOf(_x) >> "displayName") + ")"; // V1.41B01
		if (ADF_TFAR_preset && ADF_mod_TFAR) then {
			if (_g_new != _g_old) then {
				ADF_roster_userGroup = format ["<br/><font size='16' color='#D7DBD5'>%1</font>  <font color='#9DA698'>[</font><font color='#FF9E05'>%2</font><font color='#9DA698'>][</font><font color='#10D471'>%3</font><font color='#9DA698'>]<br/>", _ADF_roster_uGroupName, ADF_TFAR_LR_freq, ADF_TFAR_SW_freq];
			}
		} else { // to add ACRE2 (WIP)
			if (_g_new != _g_old) then {
				ADF_roster_userGroup = format ["<br/><font size='16' color='#D7DBD5'>%1</font><br/>", _ADF_roster_uGroupName];
			}
		};
		
		if (name _x == name player) then {
			ADF_roster_uName = "<font color='#EFCA35'>" + name _x + "<font color='#9DA698'>";
		} else {
			ADF_roster_uName = "<font color='#9DA698'>" + name _x;
		};
		ADF_roster_line =  ADF_roster_line + ADF_roster_userGroup + ADF_roster_uName + _ur + "</font><br/>";
		_g_old = group _x;
	};
} forEach ADF_roster_uArray;

// Display radio freq's?
if (ADF_TFAR_preset && ADF_mod_TFAR) then {
	ADF_roster_Intro = "<br/><br/><font size='18'>" + ADF_clanName + "</font><br/><font size='16'>Deployment Roster</font><br/><br/><font size='14' color='#d7dbd5'>Radio Frequencies</font><br/><font color='#FF9E05'>ORANGE</font><font color='#9DA698'> = team's/group's Long Range radio frequency.<br/><font color='#10D471'>GREEN</font><font color='#9DA698'> = group's Short Wave radio frequency.</font><br/><br/>";
};
if (ADF_ACRE_preset && ADF_mod_ACRE) then {
	// ACRE2 is WIP
	ADF_roster_Intro = "<br/><br/><font size='18'>" + ADF_clanName + "</font><br/><font size='16'>Deployment Roster</font><br/><br/>"
};
if (!(ADF_TFAR_preset && ADF_mod_TFAR) && !(ADF_ACRE_preset && ADF_mod_ACRE)) then {
	ADF_roster_Intro = "<br/><br/><font size='18'>" + ADF_clanName + "</font><br/><font size='16'>Deployment Roster</font><br/><br/>"
};

// Roster publish
player createDiaryRecord ["Deployment Roster",["Deployment Roster", ADF_roster_Intro + ADF_roster_line]];
ADF_set_roster = true;

// Announce call sign
if (player == leader (group player)) then {player groupChat format ["Our call sign is: %1",groupID (group player)];};

if (ADF_debug) then {["ADF_init_comm - Roster generated", false] call ADF_fnc_log};

// ADF
player createDiarySubject ["ADF", "ADF"];
player createDiaryRecord ["ADF",["ARMA Mission Development Framework", "
<img width='375' height='375' shadow='false' image='ADF\bin\images\ADF_logo.paa'/><br/><br/>
<font size='14' color='#d7dbd5'>ARMA Mission Development Framework</font><br/>
<font color='#9DA698'>ADF version: 2.06 / JUN 2018</font><br/><br/>
"]];