/*********************************************************************************
 _____ ____  _____ 
|  _  |    \|   __|
|     |  |  |   __|
|__|__|____/|__|   
ARMA Mission Development Framework
ADF version: 2.06 / JUN 2018

Script: Mission init
Author: Whiztler
Script version: 1.22

File: initServer.sqf
**********************************************************************************
DO NOT edit this file. To set-up and configure your mission, edit the files in
the  '\mission\'  folder.
*********************************************************************************/

// Reporting
if (time < 180) then {diag_log "ADF RPT: Init - executing: initServer.sqf"};

// Pre-init
#include "ADF\ADF_init_params.sqf"
#include "mission\ADF_mission_settings.sqf"
#include "ADF\ADF_init_pre.sqf"
#include "ADF\ADF_init_addons.sqf"

// Dedicated server only
if (isDedicated) then {
	#include "ADF\ADF_init_rpt.sqf"
};

// Exec mission settings
private _h = execVM "ADF\ADF_init_hc.sqf"; waitUntil {scriptDone _h}; 
if (ADF_Tickets) then {[west, _ADF_wTixNr] call BIS_fnc_respawnTickets; [east, _ADF_eTixNr] call BIS_fnc_respawnTickets};
if (_ADF_CleanUp) then {[_ADF_CleanUp_viewDist, _ADF_CleanUp_manTimer, _ADF_CleanUp_vehTimer, _ADF_CleanUp_abaTimer] execVM "ADF\ext\repCleanup\repCleanup.sqf"};
if (_ADF_Caching && !ADF_HC_connected) then {[_ADF_Caching_UnitDistance, -1, ADF_debug, _ADF_Caching_vehicleDistance_land, _ADF_Caching_vehicleDistance_air, _ADF_Caching_vehicleDistance_sea, _ADF_Caching_debugInfo] execVM "ADF\ext\zbe_cache\main.sqf"};
if (_ADF_suppliesInit) then {execVM "ADF\ADF_init_supplies.sqf"};
if (_ADF_mhq_enable) then {[_ADF_mhq_enable,_ADF_mhq_respawn_time,_ADF_mhq_respawn_nr,_ADF_mhq_respawn_class,_ADF_mhq_deploy_time,_ADF_mhq_packup_time,_ADF_wTixNr] execVM "ADF\ADF_init_mhq.sqf"};
if (ADF_missionBalance) then {execVM "ADF\ADF_init_mb.sqf";};
execVM "ADF\ADF_init_gm.sqf";

// Post-init
private _ms 	= "ADF - ARMA Mission Development Framework v";
If ((_ADF_devBuild == "Alpha") || (_ADF_devBuild == "Beta")) then {
	private _vb =  format [" (Build: %1 %2)", _ADF_devBuild, _ADF_devBuildNr];
	_ms = _ms + ADF_tpl_version + _vb;	
} else {
	_ms = _ms + ADF_tpl_version;
};

private _m = createMarker ["mADF_version",[5,-200, 0]];
_m setMarkerSize [0, 0];
_m setMarkerShape "ICON";
_m setMarkerType "mil_box";
_m setMarkerColor "ColorGrey";
_m setMarkerDir 0;
_m setMarkerText _ms;

// Create centers
if ({side _x == east} count allUnits == 0) then {createCenter east};
if ({side _x == west} count allUnits == 0) then {createCenter west};
if ({side _x == resistance} count allUnits == 0) then {createCenter resistance};
if ({side _x == independent} count allUnits == 0) then {createCenter independent};
if ({side _x == civilian} count allUnits == 0) then {createCenter civilian};

// Global texture application
if ((ADF_clanName == "Two Sierra") || (ADF_clanName == "Wolfpack")) then {execVM "mission\loadout\units\ADF_loadout_wp2s.sqf";};

// Custom mission init
execVM "Scripts\init.sqf";