//note the order in which you list things is upside down as to how it will show in the briefing on the map screen

player createDiaryRecord["Diary", ["Credits", "THIS MISSION is by |TG189| Unkl for www.TacticalGamer.com. <br/><br/>TG's scripts and functions by|TG|B, Unkl and many more for TacticalGamer.com. Some works are derivitive and can be opened for further credits."]];

player createDiaryRecord["Diary", ["PRE-COMBAT CHECKLIST", "Designate Succession of Command<br/><br/>Assign Buddy Teams<br/><br/>Designate Primary and Secondary Medics<br/><br/>Explain Casualty Action Plan<br/><br/>Designate Primary and Secondary Comms Channels<br/><br/>Brief Insertion and Exfil Plans<br/><br/>Brief Fire Support Plan<br/><br/>Brief Primary and Secondary Mission Objectives<br/><br/>Review Special Instructions<br/><br/>Review Actions on Contact<br/><br/>Assign Order of Movement<br/><br/>Brief ROE"]];
player createDiaryRecord["Diary", ["SIGNALS", "COMMAND<br/>Long Range - 50 mhz IS NOT REQUIRED, Command In-Game VON<br/>Short Range - 500 mhz<br/><br/>ALPHA-1<br/>Short Range - 100 mhz<br/><br/>ALPHA-2<br/>Short Range - 100 mhz<br/><br/>ALPHA-3<br/>Short Range - 100 mhz<br/><br/>INTER-SQUAD<br/>Secondary Net - 200 mhz<br/><br/>SUPPORTS - CAS,Artillery,Transport<br/>NONE AVAILABLE"]];


player createDiaryRecord["Diary", ["WIN/LOSE", "Win the mission by completing the objectives. Lose when all players are dead. Lose if the VIP is killed. There is no time limit."]];
player createDiaryRecord["Diary", ["CIVILIANS", "No civilians are expected within the AO."]];
player createDiaryRecord["Diary", ["WEATHER and TIME", "The time is 2000hrs. The weather is warm and clear."]];
player createDiaryRecord["Diary", ["SUPPORTS AND SUSTAINMENT", "SUPPORTS<br/>There are no additional supports available to this operation. <br/><br/>MEDICAL<br/>All players can revive but it takes 40 seconds for a non-medic and a medic is 3x faster. Revive will require a Medikit or FAK.<br/><br/>TICKETS<br/>There are only 2 respawn tickets available for each player. When these are used up the dead players will spectate. When all players are killed the mission is a failure.<br/><br/>RESUPPLY<br/>There is only the weapons and ammunition available that is already on your back. Standard loadouts apply."]];
player createDiaryRecord["Diary", ["EXECUTION", "The plan has been made to conceal your approach to the target by following the marked way points. You begin the mission on 3 assault boats and will proceed to the Boat Landing Zone (BLZ). From there, move through the waypoints on foot.<br/><br/><marker name = mrkWP1>WP1</marker> <br/><br/><marker name = mrkWP2>WP2</marker> <br/><br/><marker name = mrkWP3>WP3</marker><br/><br/>IMPORTANT NOTE<br/>Once you have the VIP you will must leave the target compound immediately as we will be dropping artillery on that location once you exfiltrate.<br/><br/>EXTRACTION<br/>You will then go to the Extraction LZ and secure the VIP until the choppers arrive."]];
player createDiaryRecord["Diary", ["FRIENDLY FORCES", "You have three teams of SOCOM units. Alpha is made up of the Squad Leader , a medic and a sniper team. Bravo and Charlie teams are the CQB Breaching teams. Team leaders have thermal night vision.<br/><br/>MISSION START<br/>You begin the mission <marker name = mrkInsertion>HERE</marker>"]];
player createDiaryRecord["Diary", ["ENEMY FORCES", "ENEMIES ON OBJECTIVE<br/>Enemy forces are expected to be spread thin as they attempt to conceal the location of the hostage. Expect a platoon sized force to be spread around the 2km region. A small squad should be on the objective building.<br/><br/>ENEMIES IN SURROUNDING AREA<br/>There are additional full squads in the surrounding villages that are expected to be part of a quick reaction force in case of a rescue attempt.<br/><br/>EXPECTED ENEMY REACTION<br/>The enemy is expected to assasinate the VIP if you are detected. They are likely to converge on your location once you are known."]];
player createDiaryRecord["Diary", ["MISSION", "Find the VIP and rescue him. His location is expected to be <marker name = mrkAO>HERE</marker>."]];
player createDiaryRecord["Diary", ["SITUATION", "A high value operator that was undercover in the corrupt police force has been discovered and taken captive."]];